### ISSUE TITLE
Review questions

### ISSUE THREAD

**Issue by pfulop** [Kinas/ReactTable#5]
https://github.com/Kinas/ReactTable/blob/6ca81a0840cdacda488d70e7d8da59a4ae802b39/src/reacttable.js#L60

Why is there an empty console.log ?

https://github.com/Kinas/ReactTable/blob/6ca81a0840cdacda488d70e7d8da59a4ae802b39/src/reacttable.js#L85

Do we need to pass props to super ? What does super do?

https://github.com/Kinas/ReactTable/blob/6ca81a0840cdacda488d70e7d8da59a4ae802b39/src/reacttable.js#L74

Can we use something else than **var**  to define variable? Should we use something else?

https://github.com/Kinas/ReactTable/blob/6ca81a0840cdacda488d70e7d8da59a4ae802b39/src/reacttable.js#L39

Could we implement the same behaviour without using **eventListeners** on the **document**? (**hint:** rows component can pass state down)

**Comment by donovantc** [comment]
@Kinas thanks for submitting your coding challenge! Overall, it looks good, there are just a couple of questions (see above) that we would like you to answer, if you don't mind. Feel free to respond here or in email.

**Comment by Kinas** [comment]
@pfulop thank you for reviewing my code!
@donovantc here are the answers to your questions:

1.) I just forgot to delete the console.log()
2.) There was no need or props in super(); I would just need props in super() when I would want to call this.props in the constructor
3.) in ES6 I should use let or const instead of var; const means that the identifier can't be reassigned and let is for variables that needs to be reassigned like in for loops 
4.) this was a tricky one. I hope my approach is okay.

**Comment by pfulop** [comment]
@Kinas Thank you for taking your time to address this issues.

1.) ✅ 
2.) ✅ 
3.) ✅ 
4.) There can be one more improvement: Pass the state changing function down trough the props. You don't have to implement this. But it's much better approach then before. 

Viktoria will get back to you soon.
